# Generated by Django 4.1.7 on 2023-08-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_information', '0001_initial'),
        ('spad_eshop_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postaddressdetail',
            name='OrderDetailSelected',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spad_eshop_order.order', verbose_name=' سبد خرید انتخابی  '),
        ),
        migrations.AddField(
            model_name='postaddressdetail',
            name='addressSelected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_information.postaddress', verbose_name=' آدرس انتخابی '),
        ),
        migrations.AddField(
            model_name='postaddress',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethodedetail',
            name='OrderDetailSelected',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spad_eshop_order.order', verbose_name=' سبد خرید انتخابی انتخابی '),
        ),
    ]
